name: Checkmarx AST Scan
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@2.0.7 #Github Action version
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: beta_nova8
          project_name: ${{ github.repository }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
